/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.ijse.carparking.vehicalinterface;

import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import java.awt.event.*;
import lk.ijse.carparking.controler.VehicalControler;

/**
 *
 * @author Evolution CS
 */

public class VehicalManage extends javax.swing.JFrame {

    /**
     * Creates new form VehicalManage
     */
    private int openIndex;
    private String count;
    private BusFrame busFrame;
    private VehicalControler vehicalcontroler;
    
    public VehicalManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vehicleBox = new javax.swing.JComboBox<>();
        memberCount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("vehical management System\n");

        vehicleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Van", "Bus", "Bicycle" }));
        vehicleBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleBoxItemStateChanged(evt);
            }
        });
        vehicleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleBoxActionPerformed(evt);
            }
        });
        vehicleBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                vehicleBoxPropertyChange(evt);
            }
        });

        memberCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberCountActionPerformed(evt);
            }
        });

        jLabel1.setText("Vehical Park");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(vehicleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(memberCount, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void vehicleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleBoxActionPerformed
        // TODO add your handling code here:
        Object selected = vehicleBox.getSelectedItem();
        vehicalcontroler=new VehicalControler();
        switch (selected.toString()) {
            case "Bus":
                openIndex=1;
                //vehicalcontroler=new VehicalControler();
                System.out.println(vehicalcontroler);
                vehicalcontroler.setbusFrame(new BusFrame());
                break;
            case "Car":
                openIndex=2;
                 //vehicalcontroler=new VehicalControler();
                vehicalcontroler.setcarFrame(new CarFrame());
                break;
            case "Van":
                openIndex=3;
                //vehicalcontroler=new VehicalControler();
                vehicalcontroler.setVanFrame(new VanFrame());
                break;
            case "Bicycle":
                openIndex=4;
                //vehicalcontroler=new VehicalControler();
                vehicalcontroler.setBicycleframe(new BicycleFrame());
                break;
            default:
                break;
        }
        
        
    }//GEN-LAST:event_vehicleBoxActionPerformed

    private void vehicleBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleBoxItemStateChanged
        // TDO add your handling code here:
    }//GEN-LAST:event_vehicleBoxItemStateChanged

    private void vehicleBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_vehicleBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleBoxPropertyChange

    private void memberCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberCountActionPerformed
        // TODO add your handling code here:
        count=memberCount.getText();
        //memberCount.setText("member selected");
        System.out.println("text selected");
        //vehicalcontroler=new VehicalControler();
        int number=Integer.parseInt(count);
        vehicalcontroler.setMemmber(number,openIndex);
       
    }//GEN-LAST:event_memberCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicalManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicalManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicalManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicalManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicalManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField memberCount;
    private javax.swing.JComboBox<String> vehicleBox;
    // End of variables declaration//GEN-END:variables
}
